### ISSUE TITLE
Throws a Syntax Error during startup

### ISSUE THREAD

**Issue by leosco** [vesparny/fair-analytics#8]
Following the instructions for programmatic integration, using Node v4.8.2 on Windows.
```
import appRoot from 'app-root-path';
import fa from 'fair-analytics';

const server = fa({
  storageDirectory: `${appRoot}/.analytics`,
});

const { feed } = server;

feed.on('ready', () => {
  server.listen(8080);
});
```
```
W20170510-17:28:59.780(-4)? (STDERR) const { json, send } = micro
W20170510-17:28:59.781(-4)? (STDERR)       ^
W20170510-17:28:59.781(-4)? (STDERR)     -
W20170510-17:28:59.782(-4)? (STDERR) SyntaxError: Unexpected token {
W20170510-17:28:59.782(-4)? (STDERR)     at exports.runInThisContext (vm.js:53:16)
W20170510-17:28:59.782(-4)? (STDERR)     at Module._compile (module.js:373:25)
W20170510-17:28:59.782(-4)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170510-17:28:59.783(-4)? (STDERR)     at Module.load (module.js:343:32)
W20170510-17:28:59.783(-4)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170510-17:28:59.783(-4)? (STDERR)     at Module.require (module.js:353:17) 
W20170510-17:28:59.783(-4)? (STDERR)     at require (internal/module.js:12:17)
W20170510-17:28:59.784(-4)? (STDERR)     at Object.<anonymous> (.\node_modules\fair-analytics\lib\fair-analytics.js:2:22)
W20170510-17:28:59.784(-4)? (STDERR)     at Module._compile (module.js:409:26)ject metadata
W20170510-17:28:59.784(-4)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)

```

**Comment by vesparny** [comment]
Hi,
Can you post the error?
Which node version are you using?

**Comment by leosco** [comment]
I updated my first comment, see above ^^^

**Comment by vesparny** [comment]
I'm afraid the minimum required node version is >=6

**Comment by vesparny** [comment]
I should probably make it clearer in the readme

**Comment by leosco** [comment]
@vesparny Sadness, that makes sense. Most of my production apps use Meteor, so the version is locked to v4 right now. Good to know! Thanks for the response

**Comment by vesparny** [comment]
I guess you can use nvm to run different node version on the same server
